# Site settings
title: Kurt Cunningham | UI/UX Designer
email: cunningham.kurt@gmail.com
description: UI/UX Design
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kurtcunningham.com"
twitter_username: "@kurtcunningham"
github_username:  kurtcunningham

# Build settings
markdown: kramdown

#Gems
gems: [bourbon, neat]

sass:
  sass_dir: _sass
  style: :compressed