# Site settings
title: Kurt Cunningham | UI/UX Designer
email: cunningham.kurt@gmail.com
description: UI/UX Design
baseurl: / # the subpath of your site, e.g. /blog/
url: kurtcunningham.com
twitter_username: "@kurtcunningham"
github_username:  kurtcunningham

#Permalink styles
permalink:           pretty
relative_permalinks: true

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"

sass:
  sass_dir: _scss
  style: :compressed

# Prose Config
prose:
  rooturl: '_posts'
  siteurl: 'http://kurtcunningham.com'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""