# Site settings
title: Kurt Cunningham | UI/UX Designer
email: cunningham.kurt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kurtcunningham.com"
twitter_username: "@kurtcunningham"
github_username:  kurtcunningham

# Build settings
markdown: kramdown

#Gems
gems: [bourbon, neat]